FROM python:3.9-slim-bullseye

RUN pip install --upgrade pip --progress-bar off

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt --progress-bar off

COPY . .

EXPOSE 5100

CMD ["python", "app.py"]