
[tool.poetry]
name = "WooduKonquer"
version = "0.1.0"
description = "Search and Reinforcement Learning algorithms for the game of WooduK"
authors = ["MNS"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
#python = "^3.10"
#gym-woodoku = {git = "https://github.com/helpingstar/gym-woodoku.git", branch = "main"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"